### ISSUE TITLE
How set local iOS framwork as Local Pod ?

### ISSUE THREAD

**Issue by CMingTseng** [realityexpander/FredsRoadtripStoryteller#10]
Hello,

Thank you for sharing your project at https://github.com/realityexpander/FredsRoadtripStoryteller.

I've been recently working with KMP+Compose as well. Currently, I'm encountering issues with loading frameworks on iOS.

Since I can only obtain framework zip files provided by third parties, I've been referencing JetBrains' documentation but haven't been able to configure it successfully.

Through a Google search, I found your project and looked into the Gradle configuration at https://github.com/realityexpander/FredsRoadtripStoryteller/blob/615575d411d7193d6063e394cf3dfb1d690803f8/shared/build.gradle.kts#L42. It seems like you've configured the framework as a local pod in the past.

I also fetched the Google Maps framework zip (https://github.com/googlemaps/google-maps-ios-utils/releases) to try configuring it, but I couldn't get your project to work after making modifications.

I've been trying to configure framework zip files for two months now and I'm stuck. Could you please provide some guidance?

this is my project 

https://github.com/cybernhl/frpc_mobile/blob/master/common/build.gradle.kts

Thank you.

**Comment by realityexpander** [comment]
Yes, I have not found a way to integrate the utils.

Only the Google Maps pod

I am waiting for google to update this for Compose.

I’m sure they are aware of the problem.

There may be a way to implement this today, but I was not able to figure it out.

Hope this helps!

Best,
Chris

**Comment by realityexpander** [comment]
I will have to close this issue for now, as I don't have a way to make a solution, and we both wait to see what Google releases.
