### ISSUE TITLE
Cocopods and multiple kotlin modules

### ISSUE THREAD

**Issue by Mats-Hjalmar** [realityexpander/FredsRoadtripStoryteller#8]
I have had issues in the past where i have a module for presentation, domain and data layer and importing google maps cocopod do not compile the shared module to swift.

I am using terratok's compose multiplatform template and importing a module with cocoapods do not build.

**Comment by realityexpander** [comment]
Check the gradle.kts, and see where the differences are… this stuff is all in flux

Im not familiar with terratok, my template is based on the one from jet brains, I include the date in the readme for the App
